# frozen_string_literal: true

require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

task default: :spec

begin
  require "yard"
  YARD::Rake::YardocTask.new
rescue LoadError
  # YARD is not available. Skip this task.
end